public with sharing class Consts
{
    public static final Integer MAX_TRACKS_PER_MIX = 20;
    public static final Integer PAGINATION_BATCH_SIZE = 10;
    public static final String EMAIL_SENDER_NAME = 'Musical Company';

    public static final String EDIT_ACCESS_LEVEL = 'Edit';
    public static final String VIEW_ACCESS_LEVEL = 'Read';

    public static final String FIELD_ID = 'Id';
    public static final String FIELD_NAME = 'Name';
    public static final String FIELD_SONG = 'Song__c';
    public static final String FIELD_MIX = 'Mix__c';
    public static final String FIELD_INDEX = 'Index__c';
    public static final String FIELD_GENRE = 'Genre__c';
    public static final String FIELD_TRACK = 'Track__c';
    public static final String AGGREGATE_COUNT = 'n';

    public static final String GENRE_ALL = 'all';
}